"""Verify six-case continuation and exact request/source locations; no admission."""
import hashlib,importlib.util,json
from pathlib import Path
imp=Path('project-first-scan/implementation');stage=imp/'data/gemma_broad_remaining_20261003'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
m=json.loads((stage/'manifest.json').read_text());result=json.loads((stage/'result.json').read_text());assert result['status']=='complete' and result['attempted_cases']==result['expected_cases']==6 and sha(stage/'rows.jsonl')==result['rows_sha256'] and sha(stage/'manifest.json')==result['manifest_sha256']
for n,h in m['input_sha256'].items():assert sha(stage/n)==h
for n,h in m['reference_sha256'].items():assert sha(Path(n))==h
spec=importlib.util.spec_from_file_location('frozen_runner',stage/'gemma_broad_remaining.py');runner=importlib.util.module_from_spec(spec);spec.loader.exec_module(runner)
cases={json.loads(s)['pmcid']:json.loads(s) for s in (stage/'cases.jsonl').read_text().splitlines()};refs={json.loads(s)['pmcid']:json.loads(s) for n in m['reference_sha256'] for s in Path(n).read_text().splitlines()};rows=[json.loads(s) for s in (stage/'rows.jsonl').read_text().splitlines()];assert len(rows)==len({r['pmcid'] for r in rows})==len(cases)==6 and not set(cases)&set(m['prior_failed_ids']);counts={'evidence_group':0,'topical_role':0,'both':0};compact=[]
for r in rows:
 c=cases[r['pmcid']];ref=refs[r['pmcid']];assert r['xml_sha256']==c['xml_sha256']==ref['xml_sha256'] and r['version']==c['version'] and r['training_admission'] is False;text,cap=runner.context(c);assert cap==r['paragraph_prefix_char_cap'] and hashlib.sha256(text.encode()).hexdigest()==r['context_sha256'];ids=[p['paragraph_index'] for p in c['paragraphs']]
 schema={'type':'object','properties':{'evidence_group':{'type':'string','enum':['clinical','review','preclinical','unresolved_or_other']},'topical_role':{'type':'string','enum':['primary','secondary_substantive','background_only','unresolved']},'design_paragraph_index':{'type':'integer','enum':ids},'topic_paragraph_index':{'type':'integer','enum':ids}},'required':['evidence_group','topical_role','design_paragraph_index','topic_paragraph_index'],'additionalProperties':False}
 request={'model':runner.MODEL,'stream':False,'think':False,'format':schema,'keep_alive':'5m','options':{'temperature':0,'seed':20261003,'num_ctx':8192,'num_predict':128},'messages':[{'role':'system','content':runner.PROMPT},{'role':'user','content':text}]};assert hashlib.sha256(json.dumps(request,sort_keys=True).encode()).hexdigest()==r['request_sha256'];v=r['response'];assert v['done'] is True and 0<v['prompt_eval_count']<=7680 and v['eval_count']<=128;parsed=json.loads(r['raw']);assert parsed==r['parsed'] and set(parsed)==set(schema['required']) and r['transport_and_location_valid'] is True
 for k in ['evidence_group','topical_role']:assert parsed[k] in schema['properties'][k]['enum'];counts[k]+=parsed[k]==ref[k]
 for k in ['design_paragraph_index','topic_paragraph_index']:assert type(parsed[k]) is int and parsed[k] in ids
 counts['both']+=all(parsed[k]==ref[k] for k in ['evidence_group','topical_role']);compact.append({'pmcid':r['pmcid'],'prediction':parsed,'draft_reference':{k:ref[k] for k in ['evidence_group','topical_role']},'elapsed_seconds':r['elapsed_seconds'],'source_context_sha256':r['context_sha256'],'narrative_character_coverage':r['narrative_characters_submitted']/r['narrative_characters_available'],'training_admission':False})
assert result['elapsed_seconds']<=1800 and result['elapsed_seconds']+m['prior_elapsed_seconds']<=2100
out={'status':'audited_complete_rejected_for_topic_scaling','cases':6,'transport_and_source_location_valid':6,'agreement_with_draft_references':counts,'compact_decisions':compact,'raw_rows_sha256':sha(stage/'rows.jsonl'),'raw_result_sha256':sha(stage/'result.json'),'manifest_sha256':sha(stage/'manifest.json'),'cumulative_broad_local_elapsed_seconds':result['elapsed_seconds']+m['prior_elapsed_seconds'],'combined_attempted_ids':7,'combined_received_responses':6,'remaining_unattempted_ids':17,'training_admission':False,'decision':'Operationally feasible shorter response, but all six predicted primary: two draft background-only and one secondary case misclassified. Do not scale or admit sources with this topic classifier.','limitations':'Six purposively selected development sources and single-agent references, not expert-gold/representative accuracy. Exact IDs do not prove evidence entailment. Multiple settings differ; no isolated causal comparison. Expansion paused for CV gap closure.'};p=imp/'gemma_broad_remaining_audit_2026-10-03.json';assert not p.exists();p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(counts))
